=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/pao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">
    <xs:include schemaLocation="deviceConfigurationCategory.xsd" />

    <xs:element name="pao">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pointFiles" type="pointFilesType" minOccurs="0" />
                <xs:element name="tags" type="tagsType" minOccurs="0">
                    <xs:unique name="tagNameUniq">
                        <xs:selector xpath="tag" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
                <xs:element name="configuration" type="DeviceCategories" minOccurs="0" />
                <xs:element name="pointInfos" type="pointInfosType" minOccurs="0">
                    <xs:unique name="pointInfoNameUniq">
                        <xs:selector xpath="pointInfo" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
                <xs:element type="commandsType" name="commands" minOccurs="0">
                    <xs:unique name="commandNameUniq">
                        <xs:selector xpath="command" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="paoType" type="xs:string" use="required" />
            <xs:attribute name="changeGroup" type="xs:string" />
            <xs:attribute name="displayGroup" type="xs:string" />
            <xs:attribute name="displayName" type="xs:string" use="required" />
            <xs:attribute name="creatable" type="xs:boolean" default="true" />
            <xs:attribute name="enabled" type="xs:boolean" default="true" />
        </xs:complexType>
    </xs:element>
    <xs:complexType name="pointFilesType">
        <xs:sequence>
            <xs:element name="pointFile" type="xs:string" maxOccurs="1" minOccurs="1" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tagType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="option" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="tagsType">
        <xs:sequence>
            <xs:element name="tag" type="tagType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="pointInfoType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="attributes" type="xs:string" />
                <xs:attribute name="init" type="xs:boolean" default="false" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="pointInfosType">
        <xs:sequence>
            <xs:element name="pointInfo" type="pointInfoType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="cmdType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="text" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="commandType">
        <xs:sequence>
            <xs:element name="cmd" type="cmdType" maxOccurs="unbounded" minOccurs="0" />
            <xs:element name="point" type="pointType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="enabled" type="xs:boolean" default="true" />
    </xs:complexType>
    <xs:complexType name="pointType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="commandsType">
        <xs:sequence>
            <xs:element name="command" type="commandType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/meter/TRANSDATA_MARKV.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="TRANSDATA_MARKV" changeGroup="electronic" displayGroup="Electronic Meters" displayName="TRANSDATA MARK-V" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>TRANSDATA_MARKV.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="METER_DETAIL_DISPLAYABLE"/>
        <tag name="SUPPORTS_ATTRIBUTE_ASSIGNMENT"/>
    </tags>
    <pointInfos>
        <pointInfo name="Peak kW (Rate A kW)" init="true" attributes="PEAK_DEMAND"/>
        <pointInfo name="Total kWh" init="true" attributes="USAGE"/>
    </pointInfos>
    <commands>
        <command name="General Scan">
            <cmd text="scan general"/>
            <point name="Total kWh"/>
        </command>
    </commands>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/meter/RFN520FAX.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="RFN520FAX" changeGroup="meter" displayGroup="RFMESH" displayName="RFN-520fAX" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>RFN.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="COMMANDER_REQUESTS"/>
        <tag name="DEVICE_CONFIGURATION"/>
        <tag name="DEVICE_ICON_TYPE" option="electric_meter"/>
        <tag name="METER_DETAIL_DISPLAYABLE"/>
        <tag name="NETWORK_MANAGER_ATTRIBUTE_READS"/>
        <tag name="OUTAGE"/>
        <tag name="RFN_DEMAND_RESET"/>
        <tag name="RFN_EVENTS"/>
        <tag name="RFN_POINT_CALCULATION"/>
        <tag name="SUPPORTS_ATTRIBUTE_ASSIGNMENT"/>
        <tag name="TOU"/>
        <tag name="USES_METER_NUMBER_FOR_MSP"/>
        <tag name="VOLTAGE_PROFILE"/>
    </tags>
    <configuration>
        <category type="rfnDemand" optional="true"/>
        <category type="demandFreeze"/>
        <category type="rfnChannelConfiguration"/>
        <category type="rfnMetrologyConfiguration" optional="true"/>
        <category type="rfnTempAlarm"/>
        <category type="rfnVoltage"/>
        <category type="tou"/>
    </configuration>
    <pointInfos>
        <pointInfo name="Avg Voltage" attributes="AVERAGE_VOLTAGE,AVERAGE_VOLTAGE_PHASE_A"/>
        <pointInfo name="Bad Upgrade Security Param" attributes="BAD_UPGRADE_SECURITY_PARAM"/>
        <pointInfo name="Blink Count" init="true" attributes="RFN_BLINK_COUNT"/>
        <pointInfo name="Blink Restore Count" init="true" attributes="RFN_BLINK_RESTORE_COUNT"/>
        <pointInfo name="Clock Error" attributes="CLOCK_ERROR"/>
        <pointInfo name="Current" attributes="CURRENT,CURRENT_PHASE_A"/>
        <pointInfo name="Daily Max Volts" init="true" attributes="MAXIMUM_VOLTAGE_DAILY"/>
        <pointInfo name="Daily Min Volts" init="true" attributes="MINIMUM_VOLTAGE_DAILY"/>
        <pointInfo name="Delivered kW" init="true" attributes="DELIVERED_DEMAND,DEMAND"/>
        <pointInfo name="Delivered kW Load Profile" attributes="LOAD_PROFILE,DELIVERED_KW_LOAD_PROFILE"/>
        <pointInfo name="Delivered kWh" init="true" attributes="USAGE,DELIVERED_KWH"/>
        <pointInfo name="Delivered kWh per Interval" init="true" attributes="DELIVERED_KWH_PER_INTERVAL"/>
        <pointInfo name="Demand Overload" attributes="DEMAND_OVERLOAD"/>
        <pointInfo name="Device Temperature" init="true" attributes="TEMPERATURE_DEVICE"/>
        <pointInfo name="Energy Accumulated While In Standby Mode" attributes="ENERGY_ACCUMULATED_WHILE_IN_STANDBY_MODE"/>
        <pointInfo name="Failed Upgrade Signature Verification" attributes="FAILED_UPGRADE_SIGNATURE_VERIF"/>
        <pointInfo name="Invalid Service" attributes="INVALID_SERVICE"/>
        <pointInfo name="Low Battery Warning" attributes="LOW_BATTERY_WARNING"/>
        <pointInfo name="Max Voltage" attributes="MAXIMUM_VOLTAGE_PHASE_A"/>
        <pointInfo name="Measurement Error" attributes="MEASUREMENT_ERROR"/>
        <pointInfo name="Min Voltage" attributes="MINIMUM_VOLTAGE_PHASE_A"/>
        <pointInfo name="Net kW Load Profile" attributes="NET_KW_LOAD_PROFILE"/>
        <pointInfo name="Net kWh" attributes="NET_KWH"/>
        <pointInfo name="Net kWh (Rate A kWh)" attributes="NET_KWH_RATE_A"/>
        <pointInfo name="Net kWh (Rate B kWh)" attributes="NET_KWH_RATE_B"/>
        <pointInfo name="Net kWh (Rate C kWh)" attributes="NET_KWH_RATE_C"/>
        <pointInfo name="Net kWh (Rate D kWh)" attributes="NET_KWH_RATE_D"/>
        <pointInfo name="Net kWh per Interval" attributes="NET_KWH_PER_INTERVAL"/>
        <pointInfo name="Non Volatile Mem Failure" attributes="NON_VOLATILE_MEM_FAILURE"/>
        <pointInfo name="Outage Count" init="true" attributes="RFN_OUTAGE_COUNT"/>
        <pointInfo name="Outage Restore Count" init="true" attributes="RFN_OUTAGE_RESTORE_COUNT"/>
        <pointInfo name="Outage Status" init="true" attributes="OUTAGE_STATUS"/>
        <pointInfo name="Outages" init="true" attributes="OUTAGE_LOG"/>
        <pointInfo name="Over Voltage" attributes="OVER_VOLTAGE"/>
        <pointInfo name="Peak Demand Daily" init="true" attributes="PEAK_DEMAND_DAILY"/>
        <pointInfo name="Peak kW" init="true" attributes="PEAK_DEMAND"/>
        <pointInfo name="Peak kW (Rate A kW)" init="true" attributes="PEAK_DEMAND_RATE_A"/>
        <pointInfo name="Peak kW (Rate B kW)" attributes="PEAK_DEMAND_RATE_B"/>
        <pointInfo name="Peak kW (Rate C kW)" attributes="PEAK_DEMAND_RATE_C"/>
        <pointInfo name="Peak kW (Rate D kW)" attributes="PEAK_DEMAND_RATE_D"/>
        <pointInfo name="Peak kW Frozen" attributes="PEAK_DEMAND_FROZEN"/>
        <pointInfo name="Peak kW Frozen (Rate A kW)" attributes="PEAK_DEMAND_FROZEN_RATE_A"/>
        <pointInfo name="Peak kW Frozen (Rate B kW)" attributes="PEAK_DEMAND_FROZEN_RATE_B"/>
        <pointInfo name="Peak kW Frozen (Rate C kW)" attributes="PEAK_DEMAND_FROZEN_RATE_C"/>
        <pointInfo name="Peak kW Frozen (Rate D kW)" attributes="PEAK_DEMAND_FROZEN_RATE_D"/>
        <pointInfo name="Power Failure" attributes="POWER_FAIL_FLAG"/>
        <pointInfo name="Ram Error" attributes="RAM_ERROR"/>
        <pointInfo name="Rate A kWh" init="true" attributes="USAGE_RATE_A"/>
        <pointInfo name="Rate B kWh" attributes="USAGE_RATE_B"/>
        <pointInfo name="Rate C kWh" attributes="USAGE_RATE_C"/>
        <pointInfo name="Rate D kWh" attributes="USAGE_RATE_D"/>
        <pointInfo name="Received kW Load Profile" attributes="RECEIVED_KW_LOAD_PROFILE"/>
        <pointInfo name="Received kWh" attributes="RECEIVED_KWH"/>
        <pointInfo name="Received kWh (Rate A kWh)" attributes="RECEIVED_KWH_RATE_A"/>
        <pointInfo name="Received kWh (Rate B kWh)" attributes="RECEIVED_KWH_RATE_B"/>
        <pointInfo name="Received kWh (Rate C kWh)" attributes="RECEIVED_KWH_RATE_C"/>
        <pointInfo name="Received kWh (Rate D kWh)" attributes="RECEIVED_KWH_RATE_D"/>
        <pointInfo name="Received kWh per Interval" attributes="RECEIVED_KWH_PER_INTERVAL"/>
        <pointInfo name="Reverse Rotation" attributes="REVERSE_POWER_FLAG"/>
        <pointInfo name="RF Demand Reset Status" init="true" attributes="RF_DEMAND_RESET_STATUS"/>
        <pointInfo name="RFN High Temperature Threshold Exceeded" attributes="RFN_TEMPERATURE_ALARM"/>
        <pointInfo name="Rom Error" attributes="ROM_ERROR"/>
        <pointInfo name="Service Disconnect Switch Error" attributes="SERVICE_DISCONNECT_SWITCH_ERROR"/>
        <pointInfo name="Service Disconnect Switch Sensor Error" attributes="SERVICE_DISCONNECT_SWITCH_SENSOR_ERROR"/>
        <pointInfo name="Stuck Switch" attributes="STUCK_SWITCH"/>
        <pointInfo name="Sum kW Load Profile" attributes="SUM_KW_LOAD_PROFILE"/>
        <pointInfo name="Sum kWh" init="true" attributes="SUM_KWH"/>
        <pointInfo name="Sum kWh (Rate A kWh)" attributes="SUM_KWH_RATE_A"/>
        <pointInfo name="Sum kWh (Rate B kWh)" attributes="SUM_KWH_RATE_B"/>
        <pointInfo name="Sum kWh (Rate C kWh)" attributes="SUM_KWH_RATE_C"/>
        <pointInfo name="Sum kWh (Rate D kWh)" attributes="SUM_KWH_RATE_D"/>
        <pointInfo name="Sum kWh per Interval" attributes="SUM_KWH_PER_INTERVAL"/>
        <pointInfo name="Tamper Detect" attributes="TAMPER_FLAG"/>
        <pointInfo name="Tamper - No Usage over 24 hours" attributes="TAMPER_NO_USAGE_OVER_24_HOURS"/>
        <pointInfo name="Tamper - Reverse Wh Detected" attributes="TAMPER_REVERSE_WH_DETECTED"/>
        <pointInfo name="Tamper - Large Increase After Outage" attributes="TAMPER_LARGE_INCREASE_AFTER_OUTAGE"/>
        <pointInfo name="Tamper - Large Decrease After Outage" attributes="TAMPER_LARGE_DECREASE_AFTER_OUTAGE"/>
        <pointInfo name="Time Adjustment" attributes="TIME_ADJUSTMENT"/>
        <pointInfo name="Total Outage Count" init="true" attributes="BLINK_COUNT"/>
        <pointInfo name="TOU Schedule Change" attributes="TOU_SCHEDULE_CHANGE"/>
        <pointInfo name="Ultra Capacitor Bad" attributes="ULTRA_CAPACITOR_BAD"/>
        <pointInfo name="Unconfigured" attributes="UNCONFIGURED"/>
        <pointInfo name="Under Voltage" attributes="UNDER_VOLTAGE"/>
        <pointInfo name="Unprogrammed" attributes="UNPROGRAMMED"/>
        <pointInfo name="User Programmable Temperature Threshold Exceeded" attributes="USER_PROGRAMMABLE_TEMPERATURE_THRESHOLD_EXCEEDED"/>
        <pointInfo name="Vibration or Tilt or Insertion - Tamper Detect" attributes="VIBRATION_TILT_TAMPER_DETECTED"/>
        <pointInfo name="Voltage" init="true" attributes="VOLTAGE,VOLTAGE_PROFILE"/>
        <pointInfo name="Voltage (Single Phase)" attributes="VOLTAGE_PHASE_A"/>
        <pointInfo name="Voltage Alerts" attributes="VOLTAGE_ALERTS"/>
        <pointInfo name="Voltage Phase A Out" attributes="VOLTAGE_PHASE_A_OUT"/>
        <pointInfo name="Voltage Phase B Out" attributes="VOLTAGE_PHASE_B_OUT"/>
        <pointInfo name="Voltage Phase C Out" attributes="VOLTAGE_PHASE_C_OUT"/>
        <pointInfo name="Voltage Phase Error" attributes="VOLTAGE_PHASE_ERROR"/>
        <pointInfo name="Received kW" attributes="RECEIVED_DEMAND"/>
        <pointInfo name="Received Peak kW" attributes="RECEIVED_PEAK_DEMAND"/>
        <pointInfo name="Received Peak kW (Rate A kW)" attributes="RECEIVED_PEAK_DEMAND_RATE_A"/>
        <pointInfo name="Received Peak kW (Rate B kW)" attributes="RECEIVED_PEAK_DEMAND_RATE_B"/>
        <pointInfo name="Received Peak kW (Rate C kW)" attributes="RECEIVED_PEAK_DEMAND_RATE_C"/>
        <pointInfo name="Received Peak kW (Rate D kW)" attributes="RECEIVED_PEAK_DEMAND_RATE_D"/>
    </pointInfos>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/transmitter/REPEATER.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="REPEATER" changeGroup="repeater" displayGroup="Signal Transmitters" displayName="REPEATER 900" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>TRANSMITTER.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="COMMANDER_REQUESTS"/>
        <tag name="DEVICE_ICON_TYPE" option="transmitter"/>
        <tag name="DLC_ADDRESS_RANGE_ENFORCE" option="464-4302,4190464-4194302"/>
        <tag name="LOCATE_ROUTE"/>
    </tags>
    <pointInfos>
        <pointInfo name="Comm Status" init="true" attributes="COMM_STATUS"/>
    </pointInfos>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/meter/RFN430SL0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" aaid="RFN430SL0" changeGroup="meter" displayGroup="RFMESH" displayName="RFN-430SL0" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>RFN.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="COMMANDER_REQUESTS"/>
        <tag name="DEVICE_CONFIGURATION"/>
        <tag name="DEVICE_ICON_TYPE" option="electric_meter"/>
        <tag name="METER_DETAIL_DISPLAYABLE"/>
        <tag name="NETWORK_MANAGER_ATTRIBUTE_READS"/>
        <tag name="OUTAGE"/>
        <tag name="RFN_DEMAND_RESET"/>
        <tag name="RFN_EVENTS"/>
        <tag name="RFN_POINT_CALCULATION"/>
        <tag name="USES_METER_NUMBER_FOR_MSP"/>
    </tags>
    <configuration>
        <category type="rfnChannelConfiguration"/>
        <category type="rfnTempAlarm"/>
    </configuration>
    <pointInfos>
        <pointInfo name="Alternate Mode Entry" zzattributes="ALTERNATE_MODE_ENTRY"/>
        <pointInfo name="ANSI Security Failed" zzattributes="ANSI_SECURITY_FAILED"/>
        <pointInfo name="Bad Upgrade Security Param" zzattributes="BAD_UPGRADE_SECURITY_PARAM"/>
        <pointInfo name="Blink Count" yyinit="true" zzattributes="RFN_BLINK_COUNT"/>
        <pointInfo name="Blink Restore Count" yyinit="true" zzattributes="RFN_BLINK_RESTORE_COUNT"/>
        <pointInfo name="Configuration Error" zzattributes="CONFIGURATION_ERROR"/>
        <pointInfo name="Current Waveform Distortion" zzattributes="CURRENT_WAVEFORM_DISTORTION"/>
        <pointInfo name="Delivered kW Load Profile" zzattributes="LOAD_PROFILE,DELIVERED_KW_LOAD_PROFILE"/>
        <pointInfo name="Delivered kWh" yyinit="true" zzattributes="USAGE,DELIVERED_KWH"/>
        <pointInfo name="Delivered kWh per Interval" yyinit="true" zzattributes="DELIVERED_KWH_PER_INTERVAL"/>
        <pointInfo name="Demand Overload" zzattributes="DEMAND_OVERLOAD"/>
        <pointInfo name="Demand Reads And Reset" zzattributes="DEMAND_READS_AND_RESET"/>
        <pointInfo name="Failed Upgrade Signature Verification" zzattributes="FAILED_UPGRADE_SIGNATURE_VERIF"/>
        <pointInfo name="Inactive Phase Current Diagnostic Error" zzattributes="INACTIVE_PHASE_CURRENT_DIAGNOSTIC_ERROR"/>
        <pointInfo name="Low Battery Warning" zzattributes="LOW_BATTERY_WARNING"/>
        <pointInfo name="Low Loss Potential" zzattributes="LOW_LOSS_POTENTIAL"/>
        <pointInfo name="Mass Memory Error" zzattributes="MASS_MEMORY_ERROR"/>
        <pointInfo name="Meter Reconfigure" zzattributes="METER_RECONFIGURE"/>
        <pointInfo name="Metrology Communication Failure" zzattributes="METROLOGY_COMM_FAILURE"/>
        <pointInfo name="Non Volatile Mem Failure" zzattributes="NON_VOLATILE_MEM_FAILURE"/>
        <pointInfo name="Outage Count" yyinit="true" zzattributes="RFN_OUTAGE_COUNT"/>
        <pointInfo name="Outage Restore Count" yyinit="true" zzattributes="RFN_OUTAGE_RESTORE_COUNT"/>
        <pointInfo name="Outage Status" yyinit="true" zzattributes="OUTAGE_STATUS"/>
        <pointInfo name="Outages" yyinit="true" zzattributes="OUTAGE_LOG"/>
        <pointInfo name="Phase Angle Displacement" zzattributes="PHASE_ANGLE_DISPLACEMENT"/>
        <pointInfo name="Phase Loss" zzattributes="PHASE_LOSS"/>
        <pointInfo name="Polarity Cross-phase and Energy Flow Diagnostic" zzattributes="POLARITY_CROSS_PHASE_ENERGY_FLOW_DIAGNOSTIC"/>
        <pointInfo name="Power Failure" zzattributes="POWER_FAIL_FLAG"/>
        <pointInfo name="Ram Error" zzattributes="RAM_ERROR"/>
        <pointInfo name="Register Full-scale Exceeded" zzattributes="REGISTER_FULL_SCALE_EXCEEDED"/>
        <pointInfo name="Reverse Rotation" zzattributes="REVERSE_POWER_FLAG"/>
        <pointInfo name="RF Demand Reset Status" yyinit="true" zzattributes="RF_DEMAND_RESET_STATUS"/>
        <pointInfo name="Rom Error" zzattributes="ROM_ERROR"/>
        <pointInfo name="Season Change" zzattributes="SEASON_CHANGE"/>
        <pointInfo name="SiteScan Error" zzattributes="SITESCAN_ERROR"/>
        <pointInfo name="THD V or TDD I Error" zzattributes="THD_V_OR_TDD_I_ERROR"/>
        <pointInfo name="Total Outage Count" yyinit="true" zzattributes="BLINK_COUNT"/>
        <pointInfo name="TOU Schedule Error" zzattributes="TOU_SCHEDULE_ERROR"/>
        <pointInfo name="Unprogrammed" zzattributes="UNPROGRAMMED"/>
    </pointInfos>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/system/WEATHER_LOCATION.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="WEATHER_LOCATION" displayName="WEATHER LOCATION" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>WEATHER_LOCATION.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="DB_EDITOR_INCOMPATIBLE"/>
    </tags>
    <pointInfos>
        <pointInfo name="Relative Humidity" init="true" attributes="HUMIDITY"/>
        <pointInfo name="Temperature" init="true" attributes="TEMPERATURE"/>
    </pointInfos>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/capControl/CAPBANKCONTROLLER.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="CAPBANKCONTROLLER" changeGroup="cap" displayGroup="Volt/Var" displayName="CBC Versacom" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>CAP_CONTROL.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="COMMANDER_REQUESTS"/>
        <tag name="DLC_ADDRESS_RANGE" option="700000001-701000000"/>
        <tag name="ONE_WAY_DEVICE"/>
    </tags>
    <pointInfos>
        <pointInfo name="Capacitor Bank State" init="true" attributes="CONTROL_POINT"/>
    </pointInfos>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/loadManagement/LM_NEST_PROGRAM.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="LM_NEST_PROGRAM" displayGroup="Demand Response" displayName="LM NEST PROGRAM" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>LM.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="NEST_PROGRAM_ENROLLMENT"/>
        <tag name="LM_PROGRAM"/>
        <tag name="SUPPORTS_PING"/>
    </tags>
    <pointInfos>
        <pointInfo name="Available Load Reduction" attributes="AVAILABLE_LOAD_REDUCTION"/>
        <pointInfo name="Connected Load" attributes="CONNECTED_LOAD"/>
        <pointInfo name="Diversified Load" attributes="DIVERSIFIED_LOAD"/>
        <pointInfo name="Max Load Reduction" attributes="MAX_LOAD_REDUCTION"/>
        <pointInfo name="Status" init="true" attributes="CONTROL_STATUS"/>
    </pointInfos>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/meter/MCT318.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="MCT318" changeGroup="meter" creatable="false" displayGroup="MCT" displayName="MCT-318" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>MCT31X.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="COMMANDER_REQUESTS"/>
        <tag name="DEVICE_ICON_TYPE" option="electric_meter"/>
        <tag name="DLC_ADDRESS_RANGE_ENFORCE" option="0-4194303"/>
        <tag name="LOCATE_ROUTE"/>
        <tag name="MCT_300_SERIES"/>
        <tag name="METER_DETAIL_DISPLAYABLE"/>
        <tag name="OUTAGE"/>
        <tag name="PORTER_COMMAND_REQUESTS"/>
        <tag name="STARS_ACCOUNT_ATTACHABLE_METER"/>
        <tag name="USES_METER_NUMBER_FOR_MSP"/>
    </tags>
    <pointInfos>
        <pointInfo name="Blink Count" init="true" attributes="BLINK_COUNT"/>
        <pointInfo name="Comm Status" attributes="COMM_STATUS"/>
        <pointInfo name="kW" init="true" attributes="DEMAND"/>
        <pointInfo name="kW (Channel 2)"/>
        <pointInfo name="kW (Channel 3)"/>
        <pointInfo name="kWh" init="true" attributes="USAGE"/>
        <pointInfo name="kWh (Channel 2)"/>
        <pointInfo name="kWh (Channel 3)"/>
        <pointInfo name="Max OR Off Peak Demand (Pulse Input 1)" attributes="PEAK_DEMAND"/>
        <pointInfo name="Max OR Off Peak Demand (Pulse Input 2)"/>
        <pointInfo name="Max OR Off Peak Demand (Pulse Input 3)"/>
        <pointInfo name="Min OR On Peak Demand (Pulse Input 1)"/>
        <pointInfo name="Min OR On Peak Demand (Pulse Input 2)"/>
        <pointInfo name="Min OR On Peak Demand (Pulse Input 3)"/>
        <pointInfo name="Outage Status" init="true" attributes="OUTAGE_STATUS"/>
        <pointInfo name="Over Flow Flag"/>
        <pointInfo name="Power Fail" init="true"/>
        <pointInfo name="Pulse Input #1 (Frozen)"/>
        <pointInfo name="Pulse Input #2 (Frozen)"/>
        <pointInfo name="Pulse Input #3 (Frozen)"/>
        <pointInfo name="Short Power Fail Flag"/>
        <pointInfo name="Status Input #2"/>
        <pointInfo name="Status Input #3"/>
        <pointInfo name="Status Input #4"/>
        <pointInfo name="Status Input #7"/>
        <pointInfo name="Status Input #8"/>
    </pointInfos>
    <commands>
        <command name="Read Blink Count">
            <cmd text="getvalue powerfail"/>
            <point name="Blink Count"/>
        </command>
        <command name="Read Current Demand">
            <cmd text="getvalue demand"/>
            <point name="kW"/>
        </command>
        <command name="Read Usage">
            <cmd text="getvalue kWh"/>
            <point name="kWh"/>
        </command>
    </commands>
</pao>
