=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/pao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">
    <xs:include schemaLocation="deviceConfigurationCategory.xsd" />

    <xs:element name="pao">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pointFiles" type="pointFilesType" minOccurs="0" />
                <xs:element name="tags" type="tagsType" minOccurs="0">
                    <xs:unique name="tagNameUniq">
                        <xs:selector xpath="tag" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
                <xs:element name="configuration" type="DeviceCategories" minOccurs="0" />
                <xs:element name="pointInfos" type="pointInfosType" minOccurs="0">
                    <xs:unique name="pointInfoNameUniq">
                        <xs:selector xpath="pointInfo" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
                <xs:element type="commandsType" name="commands" minOccurs="0">
                    <xs:unique name="commandNameUniq">
                        <xs:selector xpath="command" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="paoType" type="xs:string" use="required" />
            <xs:attribute name="changeGroup" type="xs:string" />
            <xs:attribute name="displayGroup" type="xs:string" />
            <xs:attribute name="displayName" type="xs:string" use="required" />
            <xs:attribute name="creatable" type="xs:boolean" default="true" />
            <xs:attribute name="enabled" type="xs:boolean" default="true" />
        </xs:complexType>
    </xs:element>
    <xs:complexType name="pointFilesType">
        <xs:sequence>
            <xs:element name="pointFile" type="xs:string" maxOccurs="1" minOccurs="1" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tagType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="option" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="tagsType">
        <xs:sequence>
            <xs:element name="tag" type="tagType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="pointInfoType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="attributes" type="xs:string" />
                <xs:attribute name="init" type="xs:boolean" default="false" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="pointInfosType">
        <xs:sequence>
            <xs:element name="pointInfo" type="pointInfoType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="cmdType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="text" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="commandType">
        <xs:sequence>
            <xs:element name="cmd" type="cmdType" maxOccurs="unbounded" minOccurs="0" />
            <xs:element name="point" type="pointType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="enabled" type="xs:boolean" default="true" />
    </xs:complexType>
    <xs:complexType name="pointType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="commandsType">
        <xs:sequence>
            <xs:element name="command" type="commandType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/meter/RFG301R.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="RFG301R" changeGroup="rfg" displayGroup="RFMESH" displayName="RFG-301R" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>RFG.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="COMMANDER_REQUESTS"/>
        <tag name="DEVICE_CONFIGURATION"/>
        <tag name="DEVICE_ICON_TYPE" option="gas_meter"/>
        <tag name="RFN_EVENTS"/>
        <tag name="RFN_POINT_CALCULATION"/>
        <tag name="GAS_METER_DETAIL_DISPLAYABLE"/>
        <tag name="SUPPORTS_ATTRIBUTE_ASSIGNMENT"/>
    </tags>
    <configuration>
        <category type="rfnGasChannelConfiguration"/>
    </configuration>
    <pointInfos>
        <pointInfo name="Battery Voltage" init="true" attributes="BATTERY_VOLTAGE"/>
        <pointInfo name="Gas Usage" init="true" attributes="USAGE_GAS, USAGE"/>
        <pointInfo name="Gas Usage per Interval" init="true" attributes="GAS_USAGE_PER_INTERVAL"/>
        <pointInfo name="Low Battery Warning" attributes="LOW_BATTERY_WARNING"/>
        <pointInfo name="Magnet Tampering" attributes="MAGNET_TAMPERING"/>
        <pointInfo name="Temperature" init="true" attributes="TEMPERATURE_DEVICE"/>
        <pointInfo name="Pulse 1 Switch Failure" attributes="PULSE_1_SWITCH_FAILURE"/>
        <pointInfo name="Pulse 2 Switch Failure" attributes="PULSE_2_SWITCH_FAILURE"/>
        <pointInfo name="Node Commission Event"  attributes="NODE_COMMISSION_EVENT"/>
    </pointInfos>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/capControl/CBC_7023.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="CBC_7023" changeGroup="cap2" displayGroup="Volt/Var" displayName="CBC 7023" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>702X.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="COMMANDER_REQUESTS"/>
        <tag name="DEVICE_CONFIGURATION"/>
        <tag name="TWO_WAY_DEVICE"/>
    </tags>
    <configuration>
        <category type="dnp"/>
    </configuration>
    <pointInfos>
        <pointInfo name="3 Phase kVARs" init="true"/>
        <pointInfo name="Analog Input 1" init="true" attributes="ANALOG_INPUT_ONE"/>
        <pointInfo name="Auto Volt Control" init="true" attributes="AUTO_VOLTAGE_CONTROL"/>
        <pointInfo name="Average Line Voltage" init="true" attributes="VOLTAGE"/>
        <pointInfo name="Bad Relay" init="true" attributes="BAD_RELAY"/>
        <pointInfo name="Bank Control Time" init="true"/>
        <pointInfo name="Capacitor Bank State" init="true" attributes="CONTROL_POINT"/>
        <pointInfo name="CDMA Ec/Io" init="true"/>
        <pointInfo name="CDMA Rx Power" init="true"/>
        <pointInfo name="Close Delay Time" init="true"/>
        <pointInfo name="Com Retry Delay Time" init="true"/>
        <pointInfo name="Comms Loss Time" init="true"/>
        <pointInfo name="Control Ignored Indicator" init="true" attributes="IGNORED_INDICATOR"/>
        <pointInfo name="Control Ignored Reason" init="true" attributes="IGNORED_CONTROL_REASON"/>
        <pointInfo name="Control Mode" init="true" attributes="CONTROL_MODE"/>
        <pointInfo name="Control OVUV Track Time" init="true" attributes="OVER_UNDER_VOLTAGE_TRACKING_TIME"/>
        <pointInfo name="Daily Control Limit" init="true"/>
        <pointInfo name="Daily Max Ops" init="true" attributes="DAILY_MAX_OPERATION"/>
        <pointInfo name="Delta Voltage" init="true" attributes="DELTA_VOLTAGE"/>
        <pointInfo name="Device Reset Indicator" init="true"/>
        <pointInfo name="DST Active" init="true" attributes="DST_ACTIVE"/>
        <pointInfo name="Emergency OV Threshold" init="true"/>
        <pointInfo name="Emergency OVUV Track Time" init="true"/>
        <pointInfo name="Emergency UV Threshold" init="true"/>
        <pointInfo name="Firmware Version" init="true" attributes="FIRMWARE_VERSION"/>
        <pointInfo name="High Voltage" init="true" attributes="HIGH_VOLTAGE"/>
        <pointInfo name="IP Address" init="true" attributes="IP_ADDRESS"/>
        <pointInfo name="Last Control - Analog" init="true" attributes="LAST_CONTROL_REASON_ANALOG"/>
        <pointInfo name="Last Control - Local" init="true" attributes="LAST_CONTROL_REASON_LOCAL"/>
        <pointInfo name="Last Control - Neutral Fault" init="true" attributes="LAST_CONTROL_REASON_NEUTRAL_FAULT"/>
        <pointInfo name="Last Control - OVUV" init="true" attributes="LAST_CONTROL_REASON_OVUV"/>
        <pointInfo name="Last Control - Remote" init="true" attributes="LAST_CONTROL_REASON_REMOTE"/>
        <pointInfo name="Last Control - Scheduled" init="true" attributes="LAST_CONTROL_REASON_SCHEDULED"/>
        <pointInfo name="Last Control - Temperature" init="true" attributes="LAST_CONTROL_REASON_TEMPERATURE"/>
        <pointInfo name="Last Control - VAR" init="true" attributes="LAST_CONTROL_REASON_DIGITAL"/>
        <pointInfo name="Low Voltage" init="true" attributes="LOW_VOLTAGE"/>
        <pointInfo name="Neutral Current Alarm Threshold" init="true" attributes="NEUTRAL_CURRENT_ALARM_THRESHOLD"/>
        <pointInfo name="Neutral Current Fault" init="true" attributes="NEUTRAL_CURRENT_FAULT"/>
        <pointInfo name="Neutral Current Sensor" init="true" attributes="NEUTRAL_CURRENT_SENSOR"/>
        <pointInfo name="Neutral Lockout" init="true" attributes="NEUTRAL_LOCKOUT"/>
        <pointInfo name="Op Failed - Neutral Current" init="true" attributes="OPERATION_FAILED_NEUTRAL_CURRENT"/>
        <pointInfo name="OV Condition" init="true" attributes="OVER_VOLTAGE"/>
        <pointInfo name="OV Op Count" init="true" attributes="OVER_VOLTAGE_COUNT"/>
        <pointInfo name="OV Threshold" init="true" attributes="OVER_VOLTAGE_THRESHOLD"/>
        <pointInfo name="Power Flow" init="true"/>
        <pointInfo name="Re-Close Blocked" init="true" attributes="RECLOSE_BLOCKED"/>
        <pointInfo name="Re-Close Delay Time" init="true"/>
        <pointInfo name="RSSI" init="true" attributes="RADIO_SIGNAL_STRENGTH_INDICATOR"/>
        <pointInfo name="Season One Control" init="true" attributes="TIME_TEMP_CONTROL_SEASON_ONE"/>
        <pointInfo name="Season Two Control" init="true" attributes="TIME_TEMP_CONTROL_SEASON_TWO"/>
        <pointInfo name="Temp Alarm" init="true" attributes="TEMPERATURE_ALARM"/>
        <pointInfo name="Temperature" init="true" attributes="TEMPERATURE_DEVICE"/>
        <pointInfo name="Total Op Count" init="true" attributes="TOTAL_OPERATION_COUNT"/>
        <pointInfo name="Trip Delay Time" init="true"/>
        <pointInfo name="True VAR RMS Current" init="true"/>
        <pointInfo name="UDP Port" init="true" attributes="UDP_PORT"/>
        <pointInfo name="UV Condition" init="true" attributes="UNDER_VOLTAGE"/>
        <pointInfo name="UV Op Count" init="true" attributes="UNDER_VOLTAGE_COUNT"/>
        <pointInfo name="UV Threshold" init="true" attributes="UNDER_VOLTAGE_THRESHOLD"/>
        <pointInfo name="VAR 1 Phase kVA" init="true"/>
        <pointInfo name="VAR 1 Phase kWatts" init="true"/>
        <pointInfo name="VAR Alarm" init="true"/>
        <pointInfo name="VAR Close Point" init="true"/>
        <pointInfo name="Var Control" init="true" attributes="VAR_CONTROL"/>
        <pointInfo name="VAR Power Factor" init="true"/>
        <pointInfo name="VAR RMS Voltage" init="true"/>
        <pointInfo name="VAR Trip Point" init="true"/>
        <pointInfo name="Voltage Control" init="true" attributes="VOLTAGE_CONTROL"/>
        <pointInfo name="Voltage Delta Abnormal" init="true" attributes="VOLTAGE_DELTA_ABNORMAL"/>
        <pointInfo name="Yukon Poll Time" init="true"/>
    </pointInfos>
    <commands>
        <command name="Integrity Scan">
            <cmd text="scan integrity"/>
            <point name="Capacitor Bank State"/>
            <point name="Neutral Current Sensor"/>
            <point name="Firmware Version"/>
            <point name="UDP Port"/>
            <point name="IP Address"/>
        </command>
    </commands>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/meter/MCT370.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" aaid="MCT370" changeGroup="meter" displayGroup="MCT" displayName="MCT-370" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>MCT370.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="COMMANDER_REQUESTS"/>
        <tag name="DEVICE_ICON_TYPE" option="electric_meter"/>
        <tag name="DLC_ADDRESS_RANGE_ENFORCE" option="0-4194303"/>
        <tag name="LOCATE_ROUTE"/>
        <tag name="MCT_300_SERIES"/>
        <tag name="METER_DETAIL_DISPLAYABLE"/>
        <tag name="OUTAGE"/>
        <tag name="PORTER_COMMAND_REQUESTS"/>
        <tag name="STARS_ACCOUNT_ATTACHABLE_METER"/>
        <tag name="USES_METER_NUMBER_FOR_MSP"/>
    </tags>
    <pointInfos>
        <pointInfo name="Blink Count" yyinit="true" zzattributes="BLINK_COUNT"/>
        <pointInfo name="Comm Status" zzattributes="COMM_STATUS"/>
        <pointInfo name="kVAh"/>
        <pointInfo name="kVArh"/>
        <pointInfo name="kW" yyinit="true"/>
        <pointInfo name="kW (Channel 2)"/>
        <pointInfo name="kW (Channel 3)"/>
        <pointInfo name="kWh" yyinit="true"/>
        <pointInfo name="kWh (Channel 2)"/>
        <pointInfo name="kWh (Channel 3)"/>
        <pointInfo name="Last Interval kVAr" zzattributes="KVAR"/>
        <pointInfo name="Last Interval kW" yyinit="true" zzattributes="DEMAND"/>
        <pointInfo name="Last Interval/Instantaneous kVA"/>
        <pointInfo name="Max OR Off Peak Demand (Pulse Input 1)"/>
        <pointInfo name="Max OR Off Peak Demand (Pulse Input 2)"/>
        <pointInfo name="Max OR Off Peak Demand (Pulse Input 3)"/>
        <pointInfo name="Min OR On Peak Demand (Pulse Input 1)"/>
        <pointInfo name="Min OR On Peak Demand (Pulse Input 2)"/>
        <pointInfo name="Min OR On Peak Demand (Pulse Input 3)"/>
        <pointInfo name="Neutral Current"/>
        <pointInfo name="Outage Status" yyinit="true" zzattributes="OUTAGE_STATUS"/>
        <pointInfo name="Over Flow Flag"/>
        <pointInfo name="Peak kVA (Rate A kVA)"/>
        <pointInfo name="Peak kVA (Rate B kVA)"/>
        <pointInfo name="Peak kVA (Rate C kVA)"/>
        <pointInfo name="Peak kVA (Rate D kVA)"/>
        <pointInfo name="Peak kVAr (Rate A kVAr)"/>
        <pointInfo name="Peak kVAr (Rate B kVAr)"/>
        <pointInfo name="Peak kVAr (Rate C kVAr)"/>
        <pointInfo name="Peak kVAr (Rate D kVAr)"/>
        <pointInfo name="Peak kW (Rate A kW)" yyinit="true" zzattributes="PEAK_DEMAND"/>
        <pointInfo name="Peak kW (Rate B kW)"/>
        <pointInfo name="Peak kW (Rate C kW)"/>
        <pointInfo name="Peak kW (Rate D kW)"/>
        <pointInfo name="Phase A Voltage"/>
        <pointInfo name="Phase B Voltage"/>
        <pointInfo name="Phase C Voltage"/>
        <pointInfo name="Power Fail" yyinit="true"/>
        <pointInfo name="Pulse Input #1 (Frozen)"/>
        <pointInfo name="Pulse Input #2 (Frozen)"/>
        <pointInfo name="Pulse Input #3 (Frozen)"/>
        <pointInfo name="Rate A kVAh"/>
        <pointInfo name="Rate A kVArh"/>
        <pointInfo name="Rate A kWh" yyinit="true"/>
        <pointInfo name="Rate B kVAh"/>
        <pointInfo name="Rate B kVArh"/>
        <pointInfo name="Rate B kWh"/>
        <pointInfo name="Rate C kVAh"/>
        <pointInfo name="Rate C kVArh"/>
        <pointInfo name="Rate C kWh"/>
        <pointInfo name="Rate D kVAh"/>
        <pointInfo name="Rate D kVArh"/>
        <pointInfo name="Rate D kWh"/>
        <pointInfo name="Short Power Fail Flag"/>
        <pointInfo name="Status of A relay"/>
        <pointInfo name="Status of B relay"/>
        <pointInfo name="Total kWh" yyinit="true" zzattributes="USAGE"/>
    </pointInfos>
    <commands>
        <command name="Read Blink Count">
            <cmd text="getvalue powerfail"/>
            <point name="Blink Count"/>
        </command>
        <command name="Read Current Demand">
            <cmd text="getvalue demand"/>
            <point name="kW"/>
        </command>
        <command name="Read IED Last Interval Demand">
            <cmd text="getvalue ied demand"/>
            <point name="Last Interval kW"/>
        </command>
        <command name="Read IED kWh/kW">
            <cmd text="getvalue ied kwht"/>
            <point name="Total kWh"/>
        </command>
        <command name="Read Rate A kWh/Peak kW">
            <cmd text="getvalue ied kwha"/>
            <point name="Peak kW (Rate A kW)"/>
            <point name="Rate A kWh"/>
        </command>
        <command name="Read Usage">
            <cmd text="getvalue kWh"/>
            <point name="kWh"/>
        </command>
    </commands>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/meter/RFN440_2131TD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="RFN440_2131TD" changeGroup="meter" creatable="false" displayGroup="RFMESH" displayName="RFN-440-2131TD" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>RFN.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="DEVICE_ICON_TYPE" option="electric_meter"/>
        <tag name="DISCONNECT_RFN"/>
        <tag name="METER_DETAIL_DISPLAYABLE"/>
        <tag name="NETWORK_MANAGER_ATTRIBUTE_READS"/>
        <tag name="OUTAGE"/>
        <tag name="RFN_DEMAND_RESET"/>
        <tag name="RFN_EVENTS"/>
        <tag name="TOU"/>
        <tag name="USES_METER_NUMBER_FOR_MSP"/>
    </tags>
    <pointInfos>
        <pointInfo name="Amps Phase A" init="true" attributes="CURRENT_PHASE_A"/>
        <pointInfo name="Blink Count" init="true" attributes="RFN_BLINK_COUNT"/>
        <pointInfo name="Blink Restore Count" init="true" attributes="RFN_BLINK_RESTORE_COUNT"/>
        <pointInfo name="Current Angle Phase A" attributes="CURRENT_ANGLE_PHASE_A"/>
        <pointInfo name="Delivered kWh" init="true" attributes="USAGE"/>
        <pointInfo name="Delivered kWh per Interval" init="true" attributes="USAGE_PER_INTERVAL"/>
        <pointInfo name="Device Temperature" init="true" attributes="TEMPERATURE_DEVICE"/>
        <pointInfo name="Disconnect Status" init="true" attributes="DISCONNECT_STATUS"/>
        <pointInfo name="Forward Capacitive kVArh per Interval" init="true" attributes="FORWARD_CAPACITIVE_KVARH_PER_INTERVAL"/>
        <pointInfo name="Forward Inductive kVArh" init="true" attributes="FORWARD_INDUCTIVE_KVARH"/>
        <pointInfo name="Forward Inductive kVArh per Interval" init="true" attributes="FORWARD_INDUCTIVE_KVARH_PER_INTERVAL"/>
        <pointInfo name="Last Interval kW" init="true" attributes="DEMAND"/>
        <pointInfo name="Outage Count" init="true" attributes="RFN_OUTAGE_COUNT"/>
        <pointInfo name="Outage Restore Count" init="true" attributes="RFN_OUTAGE_RESTORE_COUNT"/>
        <pointInfo name="Outage Status" init="true" attributes="OUTAGE_STATUS"/>
        <pointInfo name="Outages" init="true" attributes="OUTAGE_LOG"/>
        <pointInfo name="Peak kW" init="true" attributes="PEAK_DEMAND"/>
        <pointInfo name="Rate A kWh" init="true" attributes="USAGE_RATE_A"/>
        <pointInfo name="Rate B kWh" init="true" attributes="USAGE_RATE_B"/>
        <pointInfo name="Rate C kWh" init="true" attributes="USAGE_RATE_C"/>
        <pointInfo name="Rate D kWh" init="true" attributes="USAGE_RATE_D"/>
        <pointInfo name="Received kWh" init="true" attributes="RECEIVED_KWH"/>
        <pointInfo name="Received kWh per Interval" attributes="RECEIVED_KWH_PER_INTERVAL"/>
        <pointInfo name="Reverse Capacitive kVArh per Interval" init="true" attributes="REVERSE_CAPACITIVE_KVARH_PER_INTERVAL"/>
        <pointInfo name="Reverse Inductive kVArh" init="true" attributes="REVERSE_INDUCTIVE_KVARH"/>
        <pointInfo name="Reverse Inductive kVArh per Interval" init="true" attributes="REVERSE_INDUCTIVE_KVARH_PER_INTERVAL"/>
        <pointInfo name="RF Demand Reset Status" init="true" attributes="RF_DEMAND_RESET_STATUS"/>
        <pointInfo name="RFN High Temperature Threshold Exceeded" attributes="RFN_TEMPERATURE_ALARM"/>
        <pointInfo name="Total Outage Count" init="true" attributes="BLINK_COUNT"/>
        <pointInfo name="Volts Phase A" init="true" attributes="VOLTAGE"/>
    </pointInfos>
</pao>

=== shivanip1512/test/yukon-shared/src/main/resources/pao/definition/capControl/CBC_8020.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paoType="CBC_8020" changeGroup="cap2" displayGroup="Volt/Var" displayName="CBC 8020" xsi:noNamespaceSchemaLocation="../pao.xsd">
    <pointFiles>
        <pointFile>802X.xml</pointFile>
    </pointFiles>
    <tags>
        <tag name="COMMANDER_REQUESTS"/>
        <tag name="DEVICE_CONFIGURATION"/>
        <tag name="TWO_WAY_DEVICE"/>
    </tags>
    <configuration>
        <category type="dnp"/>
        <category type="cbcHeartbeat" />
        <category type="cbcAttributeMapping" optional="true"/>
    </configuration>
    <pointInfos>
        <pointInfo name="Abnormal Delta Voltage" init="true" attributes="VOLTAGE_DELTA_ABNORMAL"/>
        <pointInfo name="Adaptive kVAr Percent Bank Size"/>
        <pointInfo name="Auto Close Delay Time" init="true"/>
        <pointInfo name="Auto Control Mode" init="true"/>
        <pointInfo name="Average Line Voltage" init="true" attributes="VOLTAGE"/>
        <pointInfo name="Average Line Voltage Time" init="true"/>
        <pointInfo name="Bad Active Close Relay" init="true"/>
        <pointInfo name="Bad Active Trip Relay" init="true"/>
        <pointInfo name="Bank Control Time" init="true"/>
        <pointInfo name="Capacitor Bank State" init="true" attributes="CONTROL_POINT"/>
        <pointInfo name="CBC-8000 Hardware Type ID" init="true"/>
        <pointInfo name="Close Op Count" init="true" attributes="CLOSE_OPERATION_COUNT"/>
        <pointInfo name="Comms Loss OV Threshold" init="true"/>
        <pointInfo name="Comms Loss Time" init="true"/>
        <pointInfo name="Comms Loss UV Threshold" init="true"/>
        <pointInfo name="CVR Mode" init="true"/>
        <pointInfo name="CVR OV Threshold" init="true"/>
        <pointInfo name="CVR UV Threshold" init="true"/>
        <pointInfo name="Daily Control Limit" init="true"/>
        <pointInfo name="Delta Voltage" init="true"/>
        <pointInfo name="Device Reset Indicator" init="true"/>
        <pointInfo name="Door Sensor Damage/Tamper" init="true"/>
        <pointInfo name="Door Status" init="true"/>
        <pointInfo name="Emergency OV Threshold" init="true"/>
        <pointInfo name="Emergency UV Threshold" init="true"/>
        <pointInfo name="Enable SCADA Override" attributes="SCADA_OVERRIDE_ENABLE"/>
        <pointInfo name="Enable OVUV Control" attributes="ENABLE_OVUV_CONTROL"/>
        <pointInfo name="Enable Temperature Control" attributes="ENABLE_TEMPERATURE_CONTROL"/>
        <pointInfo name="Enable Time Control" attributes="ENABLE_TIME_CONTROL"/>
        <pointInfo name="Enable VAR Control" attributes="ENABLE_VAR_CONTROL"/>
        <pointInfo name="Firmware Version" init="true" attributes="FIRMWARE_VERSION"/>
        <pointInfo name="Firmware Major Version" attributes="FIRMWARE_VERSION_MAJOR"/>
        <pointInfo name="Firmware Minor Version" attributes="FIRMWARE_VERSION_MINOR"/>
        <pointInfo name="High Voltage" init="true"/>
        <pointInfo name="Ignore SCADA Override Time of Day"/>
        <pointInfo name="Ignored Control Reason" init="true" attributes="IGNORED_CONTROL_REASON"/>
        <pointInfo name="IP Address" init="true" attributes="IP_ADDRESS"/>
        <pointInfo name="Last Control Reason" init="true" attributes="LAST_CONTROL_REASON"/>
        <pointInfo name="Line Voltage High" init="true"/>
        <pointInfo name="Line Voltage Low" init="true"/>
        <pointInfo name="Line Voltage THD" init="true"/>
        <pointInfo name="Low Voltage" init="true"/>
        <pointInfo name="Manual Close Delay Time" init="true"/>
        <pointInfo name="Manual Control Mode" init="true" attributes="CONTROL_MODE"/>
        <pointInfo name="Max Operation Count" init="true"/>
        <pointInfo name="Neutral Lockout" init="true" attributes="NEUTRAL_LOCKOUT"/>
        <pointInfo name="Nominal Secondary Voltage"/>
        <pointInfo name="Open Delay Time" init="true"/>
        <pointInfo name="Open Op Count" init="true" attributes="OPEN_OPERATION_COUNT"/>
        <pointInfo name="Operation Failed" init="true"/>
        <pointInfo name="OV Op Count" init="true" attributes="OVER_VOLTAGE_COUNT"/>
        <pointInfo name="OV Threshold" init="true" attributes="OVER_VOLTAGE_THRESHOLD"/>
        <pointInfo name="OVUV Control" init="true" attributes="AUTO_VOLTAGE_CONTROL"/>
        <pointInfo name="Phase A Fundamental Current Average"/>
        <pointInfo name="Phase A Fundamental Voltage Average"/>
        <pointInfo name="Phase A Reverse Power Flow"/>
        <pointInfo name="Phase A Total Current Average"/>
        <pointInfo name="Phase A Total Voltage Average"/>
        <pointInfo name="Phase B Fundamental Current Average"/>
        <pointInfo name="Phase B Fundamental Voltage Average"/>
        <pointInfo name="Phase B Reverse Power Flow"/>
        <pointInfo name="Phase B Total Current Average"/>
        <pointInfo name="Phase B Total Voltage Average"/>
        <pointInfo name="Phase C Fundamental Current Average"/>
        <pointInfo name="Phase C Fundamental Voltage Average"/>
        <pointInfo name="Phase C Reverse Power Flow"/>
        <pointInfo name="Phase C Total Current Average"/>
        <pointInfo name="Phase C Total Voltage Average"/>
        <pointInfo name="Re-Close Delay Time" init="true"/>
        <pointInfo name="Real Time Clock Battery Failure" init="true"/>
        <pointInfo name="Reclose Block" init="true" attributes="RECLOSE_BLOCKED"/>
        <pointInfo name="Relay Sense Failed" init="true"/>
        <pointInfo name="Remote Control Mode" init="true"/>
        <pointInfo name="SCADA Override" init="true" attributes="SCADA_OVERRIDE_MODE"/>
        <pointInfo name="SCADA Override Clear" attributes="SCADA_OVERRIDE_CLEAR"/>
        <pointInfo name="SCADA Override Countdown Timer" attributes="SCADA_OVERRIDE_COUNTDOWN_TIMER"/>
        <pointInfo name="SCADA Override Heartbeat" attributes="SCADA_OVERRIDE_HEARTBEAT"/>
        <pointInfo name="SCADA Override Release Time"/>
        <pointInfo name="SCADA Override Time Remaining"/>
        <pointInfo name="SCADA Override Type"/>
        <pointInfo name="Serial Number" init="true" attributes="SERIAL_NUMBER"/>
        <pointInfo name="Temperature" init="true"/>
        <pointInfo name="Temperature High" init="true"/>
        <pointInfo name="Temperature Low" init="true"/>
        <pointInfo name="Three-Phase Current Average Interval"/>
        <pointInfo name="Three-Phase Voltage Average Interval"/>
        <pointInfo name="Total Op Count" init="true" attributes="TOTAL_OPERATION_COUNT"/>
        <pointInfo name="UDP Port" init="true" attributes="UDP_PORT"/>
        <pointInfo name="UV Op Count" init="true" attributes="UNDER_VOLTAGE_COUNT"/>
        <pointInfo name="UV Threshold" init="true" attributes="UNDER_VOLTAGE_THRESHOLD"/>
        <pointInfo name="VAR Control Total Voltage"/>
        <pointInfo name="VAr Reverse Power Flow"/>
        <pointInfo name="Voltage Control Flags" init="true" attributes="VOLTAGE_CONTROL"/>
        <pointInfo name="Va Secondary"/>
        <pointInfo name="Vb Secondary"/>
        <pointInfo name="Vc Secondary"/>
    </pointInfos>
    <commands>
        <command name="Integrity Scan">
            <cmd text="scan integrity"/>
            <point name="Serial Number"/>
            <point name="Last Control Reason"/>
            <point name="Ignored Control Reason"/>
            <point name="Capacitor Bank State"/>
            <point name="UDP Port"/>
            <point name="IP Address"/>
            <point name="Firmware Version"/>
        </command>
    </commands>
</pao>
